# Docker Compose File

services:
  product-db:
    container_name: product-db
    image: mongodb/mongodb-community-server:latest
    networks:
      - backend
    ports:
      - "27017:27017"

  app-server:
    build:
      context: product-crud
      dockerfile: Dockerfile
    restart: always
    environment: 
      - NODE_ENV=production
    depends_on:
      - product-db
    networks:
      - backend
    ports:
      - "3000:3000"

networks:
  backend:

