# Docker Compose File

services:
  product-db:
    container_name: product-db
    image: mongodb/mongodb-community-server:latest
    networks:
      - backend
    ports:
      - "27017:27017"

  app-server:
    build:
      context: product-crud
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend

networks:
  backend:

